application: androidappdocs-staging
version: 1
runtime: python27
threadsafe: true
api_version: 1
# compatibility: gae-1.9.4+

# handler for local staging servers
# WARNING: NOT FOR USE IN PRODUCTION

# Use this handler definition with
# Google App Engine 1.9.4 or higher.
# NOT compatible with prior GAE versions

handlers:

# DEVELOPMENT HANDLER
- url: /(.+)
  static_files: \1
  upload: (.+)

# Direct default, blank requests
- url: /
  static_files: index.html
  upload: index.html